
version: "3"

networks:
  db:
    internal: true
  exposed:
    internal: false

services:
  writer:
    image: kaimarshland/nasanov
    build: .
    networks:
        - db
        - exposed
    ports:
      - 5240:5240
    environment:
      - MODE=writer
      - PORT=5240
      - INFLUX_HOST=${INFLUX_HOST}
      - INFLUX_PORT=${INFLUX_PASSWORD}
      - INFLUX_PROTOCOL=${INFLUX_PROTOCOL}
      - INFLUX_USERNAME=${INFLUX_USERNAME}
      - INFLUX_PASSWORD=${INFLUX_PASSWORD}
      - NASANOV_SECRET=${NASANOV_SECRET}
  reader:
    image: kaimarshland/nasanov
    build: .
    networks:
        - db
        - exposed
    expose:
      - 9090
    ports:
      - 5250:5250
    environment:
      - MODE=reader
      - PORT=5250
      - INFLUX_HOST=${INFLUX_HOST}
      - INFLUX_PORT=${INFLUX_PASSWORD}
      - INFLUX_PROTOCOL=${INFLUX_PROTOCOL}
      - INFLUX_USERNAME=${INFLUX_USERNAME}
      - INFLUX_PASSWORD=${INFLUX_PASSWORD}
      - LISTENER_HOST=reader
      - LISTENER_PORT=9090