
version: "2"

networks:
  db:
    internal: true
  exposed:
    internal: false

services:
  writer:
    build: .
    networks:
        - db
        - exposed
    ports:
      - 5240:5240
    environment:
      - MODE=writer
      - PORT=5240
      - INFLUX_HOST=influx
      - INFLUX_PASSWORD
      - NASANOV_SECRET
  reader:
    build: .
    networks:
        - db
        - exposed
    expose:
      - 9090
    ports:
      - 5250:5250
    environment:
      - MODE=reader
      - PORT=5250
      - INFLUX_HOST=influx
      - INFLUX_PASSWORD
      - LISTENER_HOST=reader
      - LISTENER_PORT=9090
  influx:
    image: influxdb
    command: influxd -config /etc/influxdb/influxdb.conf
    volumes:
        - ./:/var/lib/influxdb
        - ./influxdb.conf:/etc/influxdb/influxdb.conf:ro
    networks:
      - db
    expose:
      - 8086